[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.build]
cmds = [
  "cd Backend/sigma",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd Backend/sigma && java -Dserver.port=$PORT -Dspring.profiles.active=railway -jar target/sigma-backend.jar"
